[Interface]
PrivateKey = iNUX6NiRWlD9Zd2iX1Y8k3ByZPsYYAWUxD2Oj1Zb0WE=
Address = 10.9.0.1/24
ListenPort = 51820

[Peer]
# slot 10.9.0.2
PublicKey = ZODHCIZE+JEfnBRNlBirqnKyYyXp9wnkp/a9YsU65DQ=
AllowedIPs = 10.9.0.2/32

[Peer]
# slot 10.9.0.3
PublicKey = P6POKDoDpSFqhFwpF1eWfdX0jBwIQQ/pQsY+iAVwOlc=
AllowedIPs = 10.9.0.3/32

[Peer]
# slot 10.9.0.4
PublicKey = bYMFnoxa8BSVWIfk1ejeSiXRijjQ5C0e64Yshm9UUGY=
AllowedIPs = 10.9.0.4/32

[Peer]
# slot 10.9.0.5
PublicKey = GTTB/y0meA9k0/xpH+DaGtQ1jZqx6vYMWxSu2ZyjFEI=
AllowedIPs = 10.9.0.5/32

[Peer]
# slot 10.9.0.6
PublicKey = PzjanPO9eob2HkIco6FfvOAHr38a7G5pm5YCRzE9x2o=
AllowedIPs = 10.9.0.6/32

[Peer]
# slot 10.9.0.7
PublicKey = KsCOJaTUTffg7w3d8Bhb3J47XPGSBL7nNriVnew01Rc=
AllowedIPs = 10.9.0.7/32

[Peer]
# slot 10.9.0.8
PublicKey = ySuVgmsFqCs5Wdj0Nt+HPbuF/HQofMaq3L9X21z3cy0=
AllowedIPs = 10.9.0.8/32

[Peer]
# slot 10.9.0.9
PublicKey = ObnT6kAyLhcYgKFKJT1RJIytAfBNX8j92W6KRT5pH0A=
AllowedIPs = 10.9.0.9/32

[Peer]
# slot 10.9.0.10
PublicKey = 9pFyyHcBDjjqaQcHLFhY0k+pQwcUJjnyqnYiUAaiT0s=
AllowedIPs = 10.9.0.10/32

[Peer]
# slot 10.9.0.11
PublicKey = pEgvniQGbdlQXu4ZqRVjvsO7fIlbTvW61/n3MWIDG3M=
AllowedIPs = 10.9.0.11/32

[Peer]
# slot 10.9.0.12
PublicKey = 5wMgSHBrmareYDOtHSoHL68MZehcB/Lb/SCNjFwsmDw=
AllowedIPs = 10.9.0.12/32

[Peer]
# slot 10.9.0.13
PublicKey = J51cGnDJ5KnuGUvYGKhEod6OlPLDZf49AQOwvR7Rq1k=
AllowedIPs = 10.9.0.13/32

[Peer]
# slot 10.9.0.14
PublicKey = QmUxy/fECyd+OICmPR6BHmzGs81bq4ghZbZKIW63Q1U=
AllowedIPs = 10.9.0.14/32

[Peer]
# slot 10.9.0.15
PublicKey = mI7B5HzHfZWCNJXVihhJzm3wwuNsLpbXipZnuYOa4gg=
AllowedIPs = 10.9.0.15/32

[Peer]
# slot 10.9.0.16
PublicKey = 9cF7F0kskUv2KJXFtwR9O3zHU/r/mcAiVblxtvDE+AI=
AllowedIPs = 10.9.0.16/32

[Peer]
# slot 10.9.0.17
PublicKey = oue45Z4WZEAjg/c+XDSH7NKHKR0HfE5P5fAhcL1ZnEk=
AllowedIPs = 10.9.0.17/32
